# Generated by Django 4.1.5 on 2023-01-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Список пользователей'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='vic', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='zvr', max_length=50),
        ),
    ]
