# Generated by Django 4.1.5 on 2023-02-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_confirmemailtoken_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contact', verbose_name='Контакт'),
        ),
    ]
