# Generated by Django 4.1.5 on 2023-01-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderitem_unique_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productparameter',
            name='unique_product_parameter',
        ),
    ]
