# Generated by Django 4.1.5 on 2023-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_contact_user_alter_productinfo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
    ]
