# Generated by Django 4.1.5 on 2023-01-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_productparameter_unique_product_parameter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productinfo',
            name='unique_product_info',
        ),
    ]
